screech/__init__.py
from .app import create_app

__all__ = ['create_app']

screech/app.py
from . import extensions
from .views import views
from .api import api
from flask import Flask
import logging
import sys

def create_app(config_path='../screech.cfg'):
    app = Flask('screech')
    app.config.from_pyfile(config_path)
    configure_logging(app)
    extensions.init_app(app)
    app.register_blueprint(views)
    app.register_blueprint(api, url_prefix='/api')
    return app

def configure_logging(app):
    if app.debug:
        return

    app.logger.setLevel(logging.DEBUG)

    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    app.logger.addHandler(handler)

screech/auth.py
from functools import wraps
from flask import session, redirect, url_for, request

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        for attr in ['me', 'endpoint', 'access_token']:
           if (session.get("_micropub_{}".format(attr)) is None):
                return redirect(url_for('views.index', next=request.url))
        return f(*args, **kwargs)
    return decorated_function

def login_save_session(resp):
    session['_micropub_me'] = resp.me
    session['_micropub_endpoint'] = resp.micropub_endpoint
    session['_micropub_access_token'] = resp.access_token

screech/extensions/__init__.py
from flask_micropub import MicropubClient
from .micropub_config import MicropubConfig

micropub = MicropubClient()
micropub_config = MicropubConfig

def init_app(app):
    micropub.init_app(app, app.config["CLIENT_NAME"])

screech/views/__init__.py
from .views import views

__all__ = ['views']

screech/views/views.py
from flask import Blueprint, redirect, render_template, request, session, url_for

from ..extensions import micropub, micropub_config
from ..auth import login_required, login_save_session

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.jinja2')

@views.route('/authorize')
def authorize():
    return micropub.authorize(
        request.args.get('me'), next_url=url_for('.index'),
        scope=request.args.get('scope'))

@views.route('/micropub-callback')
@micropub.authorized_handler
def micropub_callback(resp):
    login_save_session(resp)
    mp_config = micropub_config(resp.micropub_endpoint, resp.access_token)
    session['_micropub_config'] = mp_config.mp_config
    return redirect(url_for('.new'))

@views.route('/new')
@login_required
def new():
    me = session.get('_micropub_me')
    endpoint = session.get('_micropub_endpoint')
    access_token = session.get('_micropub_access_token')
    mp_config = session.get('_micropub_config')
    return render_template(
      'new.jinja2', me=me,
      endpoint=endpoint, access_token=access_token,
      config=mp_config
    )

screech/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Screech</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/skeleton.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/screech.css') }}">

  <link rel="icon" href="{{ url_for('static', filename='images/screech-icon.png') }}" sizes="128x128" type="image/png">

  {% block head %}{% endblock %}
</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <header class="container">
  <h2><a href="{{ url_for('views.new') }}"><img class="logo" src="{{ url_for('static', filename='images/screech-icon.svg') }}" /></a> Screech - a <a href="https://www.w3.org/TR/micropub/">Micropub</a> client for podcasts</h2>
  </header>
  {% block body %}{% endblock %}

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

screech/templates/index.jinja2
{% extends "base.jinja2" %}

{% block body %}
<div class="container">
  <form action="{{ url_for('.authorize') }}" method="GET">
    <input type="hidden" name="scope" value="create" />
    <div class="row">
      <div class="six columns">
        <label for="me">Sign In Using Your Website</label>
        <input class="util-full-width" type="text" name="me" placeholder="http://example.com" autofocus />
        <input class="button-primary" type="submit" value="Sign In" />
      </div>
    </div>
  </form>
</div>
{% endblock %}

screech/templates/new.jinja2
{% extends "base.jinja2" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/tokenfield.css') }}">
<style id="shame">
  .tokenfield {
      box-sizing: border-box;
      margin-bottom: 15px;
      overflow: hidden;
  }
</style>
<script type="text/javascript" src="{{ url_for('static', filename='js/jsmediatags.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/tokenfield.min.js') }}"></script>
{% endblock %}
{% block body %}
<div class="container">
      <h3>Logged in as <strong>{{ me }}</strong></h3>
      <form method="POST" enctype="multipart/form-data" action="{{ url_for('api.publish') }}">
        <input type="hidden" name="h" value="entry" />
        <div class="row">
          <div class="two-thirds column">
            <div>
              <div class="row">
                <label for="audio">Audio File</label>
                <input type="file" name="audio" id="audio" />
                <audio id="player"></audio>
              </div>
              <div class="row">
                <label for="photo">Optional Image</label>
                <input type="file" name="photo" id="photo" />
              </div>
              <div class="row">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="util-full-width"/>
              </div>
              <div class="row">
                <label for="content">Content</label>
                <textarea name="content" id="content" class="util-full-width"></textarea>
              </div>
              <div class="row">
                <label for="category">Category</label>
                <input type="text" id="category" class="util-full-width"/>
              </div>
              <div class="row">
                <input class="button-primary" type="submit" />
              </div>
            </div>
          </div>
          <div class="one-third column">
            <strong>Audio File Metadata</strong>
            <div id="id3-auto-fields">
              {% set id3_fields = (
                ("enclosure-length", "Size (bytes)"),
                ("duration", "Duration (HH:MM:SS)"),
                ("artist", "Artist"),
                ("album", "Album"),
                ("title", "Title"),
                ("track", "Track Number"),
              ) %}
              {% for (field, label) in id3_fields %}
                <div>
                  <label for="id3-{{ field }}">{{ label }}
                    <input class="util-full-width" type="text" id="id3-{{ field }}" name="id3-{{ field }}" value="" />
                  </label>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </form>
      <script>
        document.addEventListener("DOMContentLoaded", function(){
          function setAutoField(name, value) {
            var input = document.querySelector("input#id3-" + name);
            input.value = value;
          }

          function secsToDurationString(time) {
            var mins = ~~(time / 60);
            var secs = time % 60;

            var hrs = ~~(time / 3600);
            var mins = ~~((time % 3600) / 60);
            var secs = ~~(time % 60);

            var ret = "";

            ret += (hrs < 10 ? "0" : "");
            ret += "" + hrs + ":" + (mins < 10 ? "0" : "");
            ret += "" + mins + ":" + (secs < 10 ? "0" : "");
            ret += "" + secs;
            return ret;
          }
          var jsmediatags = window.jsmediatags;
          document.getElementById("player").addEventListener(
            "canplaythrough",
            function(e){
              var duration = secsToDurationString(e.currentTarget.duration);
              setAutoField("duration", duration);
            }
          );
          document.getElementById("audio").addEventListener(
            "change",
            function(e){
              var file = e.target.files[0];
              var objUrl = URL.createObjectURL(file);
              document.getElementById("player").src = objUrl;
              console.log(file);
              jsmediatags.read(file, {
                onSuccess: function(info) {
                  console.log(info);
                  var tags = info.tags;
                  document.getElementById("name").value = tags.album + ' • ' + tags.title;
                  for (field of ['artist', 'album', 'title', 'track']) {
                    setAutoField( field, tags[field]);
                  }
                  setAutoField("enclosure-length", file.size);
                },
                onError: function(err) {
                  console.log(err.type, err.info);
                }
              });
            }
          );

          var tf = new Tokenfield({
            el: document.getElementById("category"),
            newItems: true,
            newItemName: 'category'
          });
        });

        class MicropubClient {
          constructor( endpoint, access_token, config ) {
            this.endpoint = endpoint;
            this.access_token = access_token;
            this.config = config;
          }

          // TODO: upload a file (from a file input) to the micropub endpoint,
          // if supported. do nothing if not supported?

          // TODO: bundle up the form and submit to the micropub endpoint.
          // handle HTTP return codes.
          // success: 200 (w/ content), 201 (Created), 204 (no content)
          // auth errors: 401, 403
          // other errors: 400 (Bad Request)
        }
      </script>
    </div>
</div>
{% endblock %}